apiVersion: audit.k8s.io/v1
kind: Policy
rules:
  - level: Request
    resources:
      - group: "constraints.gatekeeper.sh"
        resources: ["*"]
    omitStages:
      - RequestReceived
  - level: Request
    users: ["system:serviceaccount:gatekeeper-system:gatekeeper-admin"]
    omitStages:
      - RequestReceived
  - level: Metadata
    namespaces: ["audit-zone"]
    resources:
      - group: ""
        resources: ["pods"]
    omitStages:
      - RequestReceived
